# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Calgary Photography by Derek McBurney
email: derek@photographybyderek.com
description: Calgary, Alberta based photographer who loves to shoot and share weddings, engagements, events, people, landscapes and architecture.
keywords: "photography by derek mcburney, derek mcburney, calgary, alberta, calgary photographer, wedding photography, engagement photography, event photography, people photography, landscape photography, architecture photography"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://photographybyderek.com" # the base hostname & protocol for your site
twitter_username: derekmcb
github_username:  dmcb
permalink: /blog/:title/

# Build settings
markdown: kramdown
source: src
destination: _site
exclude: ["photos","photos-tiny"]
keep_files: ["photos"]
sass:
  style: compressed

# Collections
collections:
  photos-weddings:
    output: true
  photos-people:
    output: true
  photos-places:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: photos-weddings
    values:
      layout: portfolio
  - scope:
      path: ""
      type: photos-people
    values:
      layout: portfolio
  - scope:
      path: ""
      type: photos-places
    values:
      layout: portfolio
  - scope:
      path: ""
      type: posts
    values:
      layout: blog-detail
